/**
 * Stubi Backend REST Documentation
 * This page contains the documentation of the backend of Stubi.<h2>Repositories</h2><ul><li><a href=\"https://github.com/IT4Kids/stubi\">Stubi Frontend</a></li><li><a href=\"https://github.com/IT4Kids/stubi-backend\">Stubi Backend</a></li></ul><h2>Authentication</h2>Most of the endpoints are not public and need a proper authentication. The following is a list of tokens that can be used for testing purposes in this documentation. It is important that you use the whole token including the string \"Bearer\". Click on \"Authorize\" in the upper right corner and copy one of these tokens to authenticateyourself. All subsequent requests will then be sent together with this token.<h3>Tokens</h3><ul><li style=\"overflow-wrap: break-word;\">Admin Token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY0ODM5NTI5OX0.6M2JFiexb08iNF1D1Mj1MGw0Brqr3Kz7QWbobMW4pDQnjVfgjU7JHZ4Pkba2JINIg0CuiJBYzOfhpyo679CODg</li><li style=\"overflow-wrap: break-word;\">User Token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNjQ4Mzk0ODg0fQ.VkIApvDlHToVDa4CNjHi-I_SZ1HdYOQv3T0-iC-o-O4U3uYqUEYX7ZHOMQH2jATb3Z_Pycqp9K-SBKaB5BpAyw</li></ul>
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Type } from "class-transformer";

export function TypeNewsDTOcreationDate() {
    return Date;
}

/**
 * Provides information about a news item
 * <p></p>
 * <p></p>
 * <b>Example Model:</b><br>
 * <pre>
 * {
  "createdBy" : "Miguel Franken",
  "link" : "https://it-for-kids.org/blog/2019/12/variablen-und-ihr-zuhause",
  "body" : "Some Example Content",
  "creationDate" : "2000-01-23T04:56:07.000+00:00",
  "title" : "Some Example Title",
  "createdById" : 0
}
 * </pre>
 */
// @dynamic
export class NewsDTO { 
    /**
     * Content of the news item
     * <p>Example: Some Example Content</p>
     */
    
    
    
    body: string;
    /**
     * Full name of the news item creator
     * <p>Example: Miguel Franken</p>
     */
    
    
    
    createdBy: string;
    /**
     * The database generated user id of the news item creator
     * <p>Example: 0</p>
     */
    
    
    
    createdById: number;
    /**
     * The date the news item was created
     * <p>Example: "2000-01-23T04:56:07.000+00:00"</p>
     */
    
    @Type(TypeNewsDTOcreationDate)
    
    creationDate: Date;
    /**
     * HTTP link to another website for reference
     * <p>Example: https://it-for-kids.org/blog/2019/12/variablen-und-ihr-zuhause</p>
     */
    
    
    
    link: string;
    /**
     * Title of the news item
     * <p>Example: Some Example Title</p>
     */
    
    
    
    title: string;
}

