/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Type } from "class-transformer";

export function TypeOrdershipDate() {
    return Date;
}

/**
 * An order for a pets from the pet store
 * <p></p>
 * <p></p>
 * <b>Example Model:</b><br>
 * <pre>
 * {
  "petId" : 6,
  "quantity" : 1,
  "id" : 0,
  "shipDate" : "2000-01-23T04:56:07.000+00:00",
  "complete" : false,
  "status" : "placed"
}
 * </pre>
 */
// @dynamic
export class Order { 
    /**
     
     * <p>Example: 0</p>
     */
    
    
    
    id?: number;
    /**
     
     * <p>Example: 0</p>
     */
    
    
    
    petId?: number;
    /**
     
     * <p>Example: 0</p>
     */
    
    
    
    quantity?: number;
    /**
     
     * <p>Example: "2000-01-23T04:56:07.000+00:00"</p>
     */
    
    @Type(TypeOrdershipDate)
    
    shipDate?: Date;
    /**
     * Order Status
     * <p>Example: "placed"</p>
     */
    
    
    
    status?: Order.StatusEnum;
    /**
     
     * <p>Example: false</p>
     */
    
    
    
    complete?: boolean;
}
export namespace Order {
    export type StatusEnum = 'placed' | 'approved' | 'delivered';
    export const StatusEnum = {
        Placed: 'placed' as StatusEnum,
        Approved: 'approved' as StatusEnum,
        Delivered: 'delivered' as StatusEnum
    };
}


