/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Type } from "class-transformer";


/**
 * A tag for a pet
 * <p></p>
 * <p></p>
 * <b>Example Model:</b><br>
 * <pre>
 * {
  "name" : "name",
  "id" : 0
}
 * </pre>
 */
// @dynamic
export class Tag { 
    /**
     
     * <p>Example: 0</p>
     */
    
    
    
    id?: number;
    /**
     
     * <p>Example: "name"</p>
     */
    
    
    
    name?: string;
}

